version: '3'
services:
  myapp:
    build: .
    ports:
      - 3000:3000

  db:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
    volumes:
     - mongo-data:/data/db
    
  admin:
    image: mongo-express
    ports:
     - 8080:8081
    restart: always
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=${USERNAME}
     - ME_CONFIG_MONGODB_ADMINPASSWORD=${PASSWORD}
     - ME_CONFIG_MONGODB_SERVER=${SERVER}
volumes:
  mongo-data:
    driver: local
